<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tns="urn:ihe:iti:xcpd:2009" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsaw="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hl7="urn:hl7-org:v3" name="XCPDRespondingGateway" targetNamespace="urn:ihe:iti:xcpd:2009">
	<wsdl:documentation>WSDL for XCPD Responding Gateway</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:hl7="urn:hl7-org:v3" elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3">
			<!-- Include the message schema -->
			<xsd:include schemaLocation="schema/HL7V3/NE2008/multicacheschemas/PRPA_IN201305UV02.xsd"/>
		</xsd:schema>
		<xsd:schema xmlns:hl7="urn:hl7-org:v3" elementFormDefault="qualified" targetNamespace="urn:hl7-org:v3">
			<!-- Include the message schema -->
			<xsd:include schemaLocation="schema/HL7V3/NE2008/multicacheschemas/PRPA_IN201306UV02.xsd"/>
		</xsd:schema>
		<xsd:schema elementFormDefault="qualified" targetNamespace="urn:ihe:iti:xcpd:2009">
			<!-- Include the message schema -->
			<xsd:include schemaLocation="schema/IHE/XCPD_PLQ.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="PRPA_IN201305UV02_Message">
		<wsdl:part element="hl7:PRPA_IN201305UV02" name="Body"/>
	</wsdl:message>
	<wsdl:message name="PRPA_IN201306UV02_Message">
		<wsdl:part element="hl7:PRPA_IN201306UV02" name="Body"/>
	</wsdl:message>
	<wsdl:portType name="RespondingGateway_PortType">
		<wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
			<wsdl:input message="tns:PRPA_IN201305UV02_Message" wsaw:Action="urn:hl7-org:v3:PRPA_IN201305UV02:CrossGatewayPatientDiscovery"/>
			<wsdl:output message="tns:PRPA_IN201306UV02_Message" wsaw:Action="urn:hl7-org:v3:PRPA_IN201306UV02:CrossGatewayPatientDiscovery"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="RespondingGateway_Binding_Soap12" type="tns:RespondingGateway_PortType">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="RespondingGateway_PRPA_IN201305UV02">
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="RespondingGateway_Service">
		<wsdl:port binding="tns:RespondingGateway_Binding_Soap12" name="RespondingGateway_Port_Soap12">
			<soap12:address location="https://servername/registry/HS.IHE.XCPD.RespondingGateway.Services.cls"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
